account_view:
    path: /banking/account
    controller: App\Controller\AccountController::accountView
    methods: GET

account_transfer_in:
    path: /banking/account/transactions/deposit
    controller: App\Controller\TransactionController::deposit
    methods: GET|POST

account_transfer_out:
    path: /banking/account/transactions/transfer
    controller: App\Controller\TransactionController::transfer
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'account_view'

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register