index:
    path: /banking
    controller: App\Controller\DefaultController::index

transfer_in:
    path: /banking/transactions/deposit
    controller: App\Controller\DefaultController::deposit

transfer_out:
    path: /banking/transactions/transfer
    controller: App\Controller\DefaultController::transfer

app_logout:
    path: /logout
    methods: GET